import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import React, { Suspense } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>NoteForge - Your Notes, Organized</title>
        <meta name="description" content="NoteForge is a powerful note-taking app to organize your thoughts and ideas." />
        <meta name="keywords" content="notes, notebook, productivity, note-taking, NoteForge" />
        <meta property="og:title" content="NoteForge - Your Notes, Organized" />
        <meta property="og:description" content="NoteForge is a powerful note-taking app to organize your thoughts and ideas." />
        <meta property="og:image" content="/noteforge-logo.png" />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="NoteForge - Your Notes, Organized" />
        <meta name="twitter:description" content="NoteForge is a powerful note-taking app to organize your thoughts and ideas." />
        <meta name="twitter:image" content="/noteforge-logo.png" />
        <link rel="icon" href="/noteforge-logo.png" type="image/png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
          </ThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
